### ISSUE TITLE
Support array of directories

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/xenon-flow#26]
When I have the following output:
```
outputs:
  safar_output:
    outputSource: safar-analyze-book/safar_output_dir
    type: Directory[]
```
It does not copy the results to the output directory.

The following cannot even be executed:
```
outputs:
  safar_output:
    outputSource: safar-analyze-book/safar_output_dir
    type:
      type: array
      items: Directory
```
